version: '3'

services:
  spark-master:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./workspace:/opt/workspace
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark-network
  spark-worker-1:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    networks:
      - spark-network
  spark-worker-2:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge